/**
 * Mock Data Adapter - Using local mock data for development
 * This adapter bridges frontend UI with mock data from the seed database
 * Expanded with 30 politicians for complete UI display
 * Updated with Korean names and data (v7.0)
 * FIXED: Field names now match HotPost and PoliticianPost interfaces
 */

import type { PoliticianRanking, HotPost, PoliticianPost } from './home';

// Mock data based on seed data - 30 Politicians (Korean)
export const MOCK_POLITICIANS: PoliticianRanking[] = [
  {
    id: 1,
    name: '이준호',
    party: '국민의힘',
    region: '서울',
    position: '서울특별시장',
    category_type: '특별시장',
    political_status: '출마자',
    status: '활동중',
    claude_score: 3.5,
    gpt_score: 3.4,
    gemini_score: 3.6,
    grok_score: 3.3,
    perplexity_score: 3.5,
    composite_score: 3.46,
    member_rating: 3.2,
    member_rating_count: 2,
  },
  {
    id: 2,
    name: '한민정',
    party: '더불어민주당',
    region: '부산',
    position: '부산광역시장',
    category_type: '광역시장',
    political_status: '예비후보자',
    status: '활동중',
    claude_score: 3.6,
    gpt_score: 3.5,
    gemini_score: 3.7,
    grok_score: 3.4,
    perplexity_score: 3.6,
    composite_score: 3.56,
    member_rating: 3.28,
    member_rating_count: 3,
  },
  {
    id: 3,
    name: '오수진',
    party: '정의당',
    region: '대구',
    position: '대구광역시장',
    category_type: '도지사',
    political_status: '후보자',
    status: '활동중',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.5,
    perplexity_score: 3.7,
    composite_score: 3.66,
    member_rating: 3.36,
    member_rating_count: 4,
  },
  {
    id: 4,
    name: '이재민',
    party: '개혁신당',
    region: '인천',
    position: '인천광역시장',
    category_type: '시장',
    political_status: '당선자',
    status: '활동중',
    claude_score: 3.8,
    gpt_score: 3.7,
    gemini_score: 3.9,
    grok_score: 3.6,
    perplexity_score: 3.8,
    composite_score: 3.76,
    member_rating: 3.44,
    member_rating_count: 2,
  },
  {
    id: 5,
    name: '심상정',
    party: '조국혁신당',
    region: '광주',
    position: '광주광역시장',
    category_type: '구청장',
    political_status: '현직',
    status: '활동중',
    claude_score: 3.9,
    gpt_score: 3.8,
    gemini_score: 4.0,
    grok_score: 3.7,
    perplexity_score: 3.9,
    composite_score: 3.86,
    member_rating: 3.52,
    member_rating_count: 3,
  },
  {
    id: 6,
    name: '박영순',
    party: '국민의힘',
    region: '대전',
    position: '대전광역시장',
    category_type: '군수',
    political_status: '출마자',
    status: '활동중',
    claude_score: 4.0,
    gpt_score: 3.9,
    gemini_score: 4.1,
    grok_score: 3.8,
    perplexity_score: 4.0,
    composite_score: 3.96,
    member_rating: 3.6,
    member_rating_count: 4,
  },
  {
    id: 7,
    name: '김혜정',
    party: '더불어민주당',
    region: '울산',
    position: '울산광역시장',
    category_type: '광역의원',
    political_status: '예비후보자',
    status: '활동중',
    claude_score: 4.1,
    gpt_score: 4.0,
    gemini_score: 4.2,
    grok_score: 3.9,
    perplexity_score: 4.1,
    composite_score: 4.06,
    member_rating: 3.68,
    member_rating_count: 2,
  },
  {
    id: 8,
    name: '조동현',
    party: '정의당',
    region: '세종',
    position: '세종시장',
    category_type: '기초의원',
    political_status: '후보자',
    status: '활동중',
    claude_score: 4.2,
    gpt_score: 4.1,
    gemini_score: 4.3,
    grok_score: 4.0,
    perplexity_score: 4.2,
    composite_score: 4.16,
    member_rating: 3.76,
    member_rating_count: 3,
  },
  {
    id: 9,
    name: '윤주미',
    party: '개혁신당',
    region: '경기',
    position: '경기도지사',
    category_type: '특별시장',
    political_status: '당선자',
    status: '활동중',
    claude_score: 4.3,
    gpt_score: 4.2,
    gemini_score: 4.4,
    grok_score: 4.1,
    perplexity_score: 4.3,
    composite_score: 4.26,
    member_rating: 3.84,
    member_rating_count: 4,
  },
  {
    id: 10,
    name: '정광호',
    party: '조국혁신당',
    region: '강원',
    position: '강원도지사',
    category_type: '광역시장',
    political_status: '현직',
    status: '활동중',
    claude_score: 4.4,
    gpt_score: 4.3,
    gemini_score: 4.5,
    grok_score: 4.2,
    perplexity_score: 4.4,
    composite_score: 4.36,
    member_rating: 3.92,
    member_rating_count: 2,
  },
  {
    id: 11,
    name: '이민숙',
    party: '국민의힘',
    region: '충북',
    position: '충청북도지사',
    category_type: '도지사',
    political_status: '출마자',
    status: '활동중',
    claude_score: 3.5,
    gpt_score: 3.4,
    gemini_score: 3.6,
    grok_score: 3.3,
    perplexity_score: 3.5,
    composite_score: 3.46,
    member_rating: 3.2,
    member_rating_count: 3,
  },
  {
    id: 12,
    name: '박준영',
    party: '더불어민주당',
    region: '충남',
    position: '충청남도지사',
    category_type: '시장',
    political_status: '예비후보자',
    status: '활동중',
    claude_score: 3.6,
    gpt_score: 3.5,
    gemini_score: 3.7,
    grok_score: 3.4,
    perplexity_score: 3.6,
    composite_score: 3.56,
    member_rating: 3.28,
    member_rating_count: 4,
  },
  {
    id: 13,
    name: '허민진',
    party: '정의당',
    region: '전북',
    position: '전라북도지사',
    category_type: '구청장',
    political_status: '후보자',
    status: '활동중',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.5,
    perplexity_score: 3.7,
    composite_score: 3.66,
    member_rating: 3.36,
    member_rating_count: 2,
  },
  {
    id: 14,
    name: '강석호',
    party: '개혁신당',
    region: '전남',
    position: '전라남도지사',
    category_type: '군수',
    political_status: '당선자',
    status: '활동중',
    claude_score: 3.8,
    gpt_score: 3.7,
    gemini_score: 3.9,
    grok_score: 3.6,
    perplexity_score: 3.8,
    composite_score: 3.76,
    member_rating: 3.44,
    member_rating_count: 3,
  },
  {
    id: 15,
    name: '유영미',
    party: '조국혁신당',
    region: '경북',
    position: '경상북도지사',
    category_type: '광역의원',
    political_status: '현직',
    status: '활동중',
    claude_score: 3.9,
    gpt_score: 3.8,
    gemini_score: 4.0,
    grok_score: 3.7,
    perplexity_score: 3.9,
    composite_score: 3.86,
    member_rating: 3.52,
    member_rating_count: 4,
  },
  {
    id: 16,
    name: '이성국',
    party: '국민의힘',
    region: '경남',
    position: '경상남도지사',
    category_type: '기초의원',
    political_status: '출마자',
    status: '활동중',
    claude_score: 4.0,
    gpt_score: 3.9,
    gemini_score: 4.1,
    grok_score: 3.8,
    perplexity_score: 4.0,
    composite_score: 3.96,
    member_rating: 3.6,
    member_rating_count: 2,
  },
  {
    id: 17,
    name: '박지수',
    party: '더불어민주당',
    region: '제주',
    position: '제주도지사',
    category_type: '특별시장',
    political_status: '예비후보자',
    status: '활동중',
    claude_score: 4.1,
    gpt_score: 4.0,
    gemini_score: 4.2,
    grok_score: 3.9,
    perplexity_score: 4.1,
    composite_score: 4.06,
    member_rating: 3.68,
    member_rating_count: 3,
  },
  {
    id: 18,
    name: '김동욱',
    party: '정의당',
    region: '서울',
    position: '서울시의원',
    category_type: '광역시장',
    political_status: '후보자',
    status: '활동중',
    claude_score: 4.2,
    gpt_score: 4.1,
    gemini_score: 4.3,
    grok_score: 4.0,
    perplexity_score: 4.2,
    composite_score: 4.16,
    member_rating: 3.76,
    member_rating_count: 4,
  },
  {
    id: 19,
    name: '서정우',
    party: '개혁신당',
    region: '부산',
    position: '부산시의원',
    category_type: '도지사',
    political_status: '당선자',
    status: '활동중',
    claude_score: 4.3,
    gpt_score: 4.2,
    gemini_score: 4.4,
    grok_score: 4.1,
    perplexity_score: 4.3,
    composite_score: 4.26,
    member_rating: 3.84,
    member_rating_count: 2,
  },
  {
    id: 20,
    name: '이하나',
    party: '조국혁신당',
    region: '대구',
    position: '대구시의원',
    category_type: '시장',
    political_status: '현직',
    status: '활동중',
    claude_score: 4.4,
    gpt_score: 4.3,
    gemini_score: 4.5,
    grok_score: 4.2,
    perplexity_score: 4.4,
    composite_score: 4.36,
    member_rating: 3.92,
    member_rating_count: 3,
  },
  {
    id: 21,
    name: '조무성',
    party: '국민의힘',
    region: '인천',
    position: '인천시의원',
    category_type: '구청장',
    political_status: '출마자',
    status: '활동중',
    claude_score: 3.5,
    gpt_score: 3.4,
    gemini_score: 3.6,
    grok_score: 3.3,
    perplexity_score: 3.5,
    composite_score: 3.46,
    member_rating: 3.2,
    member_rating_count: 4,
  },
  {
    id: 22,
    name: '김현진',
    party: '더불어민주당',
    region: '광주',
    position: '광주시의원',
    category_type: '군수',
    political_status: '예비후보자',
    status: '활동중',
    claude_score: 3.6,
    gpt_score: 3.5,
    gemini_score: 3.7,
    grok_score: 3.4,
    perplexity_score: 3.6,
    composite_score: 3.56,
    member_rating: 3.28,
    member_rating_count: 2,
  },
  {
    id: 23,
    name: '박승준',
    party: '정의당',
    region: '대전',
    position: '대전시의원',
    category_type: '광역의원',
    political_status: '후보자',
    status: '활동중',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.5,
    perplexity_score: 3.7,
    composite_score: 3.66,
    member_rating: 3.36,
    member_rating_count: 3,
  },
  {
    id: 24,
    name: '이선영',
    party: '개혁신당',
    region: '울산',
    position: '울산시의원',
    category_type: '기초의원',
    political_status: '당선자',
    status: '활동중',
    claude_score: 3.8,
    gpt_score: 3.7,
    gemini_score: 3.9,
    grok_score: 3.6,
    perplexity_score: 3.8,
    composite_score: 3.76,
    member_rating: 3.44,
    member_rating_count: 4,
  },
  {
    id: 25,
    name: '정다운',
    party: '조국혁신당',
    region: '세종',
    position: '서울시의원',
    category_type: '특별시장',
    political_status: '현직',
    status: '활동중',
    claude_score: 3.9,
    gpt_score: 3.8,
    gemini_score: 4.0,
    grok_score: 3.7,
    perplexity_score: 3.9,
    composite_score: 3.86,
    member_rating: 3.52,
    member_rating_count: 2,
  },
  {
    id: 26,
    name: '이현민',
    party: '국민의힘',
    region: '경기',
    position: '부산시의원',
    category_type: '광역시장',
    political_status: '출마자',
    status: '활동중',
    claude_score: 4.0,
    gpt_score: 3.9,
    gemini_score: 4.1,
    grok_score: 3.8,
    perplexity_score: 4.0,
    composite_score: 3.96,
    member_rating: 3.6,
    member_rating_count: 3,
  },
  {
    id: 27,
    name: '김미소',
    party: '더불어민주당',
    region: '강원',
    position: '대구시의원',
    category_type: '도지사',
    political_status: '예비후보자',
    status: '활동중',
    claude_score: 4.1,
    gpt_score: 4.0,
    gemini_score: 4.2,
    grok_score: 3.9,
    perplexity_score: 4.1,
    composite_score: 4.06,
    member_rating: 3.68,
    member_rating_count: 4,
  },
  {
    id: 28,
    name: '박범수',
    party: '정의당',
    region: '충북',
    position: '인천시의원',
    category_type: '시장',
    political_status: '후보자',
    status: '활동중',
    claude_score: 4.2,
    gpt_score: 4.1,
    gemini_score: 4.3,
    grok_score: 4.0,
    perplexity_score: 4.2,
    composite_score: 4.16,
    member_rating: 3.76,
    member_rating_count: 2,
  },
  {
    id: 29,
    name: '유정현',
    party: '개혁신당',
    region: '충남',
    position: '광주시의원',
    category_type: '구청장',
    political_status: '당선자',
    status: '활동중',
    claude_score: 4.3,
    gpt_score: 4.2,
    gemini_score: 4.4,
    grok_score: 4.1,
    perplexity_score: 4.3,
    composite_score: 4.26,
    member_rating: 3.84,
    member_rating_count: 3,
  },
  {
    id: 30,
    name: '이동한',
    party: '조국혁신당',
    region: '전북',
    position: '대전시의원',
    category_type: '군수',
    political_status: '현직',
    status: '활동중',
    claude_score: 4.4,
    gpt_score: 4.3,
    gemini_score: 4.5,
    grok_score: 4.2,
    perplexity_score: 4.4,
    composite_score: 4.36,
    member_rating: 3.92,
    member_rating_count: 4,
  },
];

// Mock Hot Posts - 15 posts with CORRECT field names
export const MOCK_HOT_POSTS: HotPost[] = [
  {
    id: 1,
    title: '2024년 정치인 평가: 신뢰도 높은 리더십',
    content: '전문가 평가에 따르면 신뢰도 높은 리더십이 중요합니다. 민간 여론조사에서도 높은 지지율을 보이고 있습니다.',
    author_username: '정치 전문가',
    created_at: '2024-10-15',
    view_count: 1250,
    upvotes: 234,
    downvotes: 12,
    comment_count: 45,
    hot_score: 9.8,
    is_hot: true,
    category: '정치 분석',
  },
  {
    id: 2,
    title: '새로운 정책 발표: 청년 지원 확대',
    content: '정부가 청년층을 위한 새로운 지원 정책을 발표했습니다. 이번 정책은 취업과 창업을 동시에 지원합니다.',
    author_username: '정책 뉴스',
    created_at: '2024-10-14',
    view_count: 980,
    upvotes: 187,
    downvotes: 8,
    comment_count: 38,
    hot_score: 9.5,
    is_hot: true,
    category: '정책',
  },
  {
    id: 3,
    title: '국회 특별위원회 구성 현황',
    content: '국회에서 새로운 특별위원회가 구성되었습니다. 국방, 경제, 교육 분야에서 중점 추진될 예정입니다.',
    author_username: '정치부 기자',
    created_at: '2024-10-13',
    view_count: 850,
    upvotes: 156,
    downvotes: 5,
    comment_count: 32,
    hot_score: 9.2,
    is_hot: true,
    category: '정치',
  },
  {
    id: 4,
    title: '지역 발전과 정치인의 역할',
    content: '지역 사회 발전에 있어 정치인의 역할이 얼마나 중요한지에 대해 살펴봅니다.',
    author_username: '지역 분석가',
    created_at: '2024-10-12',
    view_count: 720,
    upvotes: 134,
    downvotes: 6,
    comment_count: 28,
    hot_score: 8.8,
    is_hot: false,
    category: '지역 정치',
  },
  {
    id: 5,
    title: '선거 제도 개혁 논의',
    content: '더욱 공정한 선거 제도를 위한 개혁안이 논의 중입니다. 투명성과 효율성을 동시에 추구합니다.',
    author_username: '선거 제도 전문가',
    created_at: '2024-10-11',
    view_count: 645,
    upvotes: 121,
    downvotes: 9,
    comment_count: 24,
    hot_score: 8.5,
    is_hot: false,
    category: '제도 개혁',
  },
  {
    id: 6,
    title: '여야 교육 정책 비교',
    content: '여당과 야당의 교육 정책을 비교 분석합니다. 각 당의 차별화된 정책 방향을 알아봅니다.',
    author_username: '교육 정책 분석가',
    created_at: '2024-10-10',
    view_count: 580,
    upvotes: 109,
    downvotes: 7,
    comment_count: 20,
    hot_score: 8.2,
    is_hot: false,
    category: '정책 비교',
  },
  {
    id: 7,
    title: '차기 지도자상 여론조사 결과',
    content: '최근 여론조사에서 차기 지도자가 갖춰야 할 덕목에 대해 국민 의견을 수렴했습니다.',
    author_username: '여론조사 기관',
    created_at: '2024-10-09',
    view_count: 520,
    upvotes: 98,
    downvotes: 4,
    comment_count: 18,
    hot_score: 7.9,
    is_hot: false,
    category: '여론조사',
  },
  {
    id: 8,
    title: '국제 관계와 한국 외교',
    content: '국제 정세 변화 속에서 한국의 외교 정책이 어떻게 전개되는지 살펴봅니다.',
    author_username: '외교 전문가',
    created_at: '2024-10-08',
    view_count: 465,
    upvotes: 87,
    downvotes: 3,
    comment_count: 16,
    hot_score: 7.6,
    is_hot: false,
    category: '외교',
  },
  {
    id: 9,
    title: '정치인 신뢰도 평가 지표',
    content: '정치인의 신뢰도를 평가하는 다양한 지표들을 분석합니다. AI 평가 시스템의 역할도 살펴봅니다.',
    author_username: '신뢰도 분석가',
    created_at: '2024-10-07',
    view_count: 410,
    upvotes: 76,
    downvotes: 5,
    comment_count: 14,
    hot_score: 7.3,
    is_hot: false,
    category: '평가',
  },
  {
    id: 10,
    title: '지속가능 발전과 정책',
    content: '환경과 경제의 균형을 맞추는 지속가능 발전 정책에 대해 논의합니다.',
    author_username: '지속가능 발전 전문가',
    created_at: '2024-10-06',
    view_count: 360,
    upvotes: 65,
    downvotes: 2,
    comment_count: 12,
    hot_score: 7.0,
    is_hot: false,
    category: '환경',
  },
  {
    id: 11,
    title: '청년세대와 정치 참여',
    content: '청년세대의 정치 참여도 증가 추세를 보이고 있습니다. 그들의 관심사와 요구사항을 알아봅니다.',
    author_username: '사회학자',
    created_at: '2024-10-05',
    view_count: 315,
    upvotes: 54,
    downvotes: 3,
    comment_count: 10,
    hot_score: 6.7,
    is_hot: false,
    category: '세대',
  },
  {
    id: 12,
    title: '정치 커뮤니케이션의 미래',
    content: '디지털 시대의 정치 커뮤니케이션이 어떻게 변화하고 있는지 살펴봅니다.',
    author_username: '커뮤니케이션 전문가',
    created_at: '2024-10-04',
    view_count: 270,
    upvotes: 43,
    downvotes: 2,
    comment_count: 8,
    hot_score: 6.4,
    is_hot: false,
    category: '미디어',
  },
  {
    id: 13,
    title: '복지 정책 효과 분석',
    content: '최근 시행된 복지 정책들의 실제 효과를 분석합니다. 시민 만족도도 함께 조사했습니다.',
    author_username: '사회복지 전문가',
    created_at: '2024-10-03',
    view_count: 225,
    upvotes: 32,
    downvotes: 1,
    comment_count: 6,
    hot_score: 6.1,
    is_hot: false,
    category: '복지',
  },
  {
    id: 14,
    title: '도시 재생 사업 현황',
    content: '전국의 도시 재생 사업이 순조롭게 진행 중입니다. 주요 사업 현황을 소개합니다.',
    author_username: '도시 계획가',
    created_at: '2024-10-02',
    view_count: 180,
    upvotes: 21,
    downvotes: 0,
    comment_count: 4,
    hot_score: 5.8,
    is_hot: false,
    category: '도시',
  },
  {
    id: 15,
    title: '과학 기술 정책 방향',
    content: '미래 먹거리 산업 발전을 위한 과학 기술 정책의 방향을 제시합니다.',
    author_username: '과학 정책가',
    created_at: '2024-10-01',
    view_count: 135,
    upvotes: 10,
    downvotes: 1,
    comment_count: 2,
    hot_score: 5.5,
    is_hot: false,
    category: '과학',
  },
];

// Mock Politician Posts - 9 posts
export const MOCK_POLITICIAN_POSTS: PoliticianPost[] = [
  {
    id: 1,
    politician_id: 1,
    politician_name: '이준호',
    politician_party: '국민의힘',
    politician_position: '서울특별시장',
    politician_status: '출마자',
    title: '주민 소통 간담회 개최',
    content: '지난주 주민 소통 간담회를 개최하여 지역 주민들의 의견을 청취했습니다. 주로 교육과 교통에 대한 의견이 많았습니다.',
    category: '소통',
    created_at: '2024-10-15',
    view_count: 450,
    upvotes: 89,
    comment_count: 15,
  },
  {
    id: 2,
    politician_id: 2,
    politician_name: '한민정',
    politician_party: '더불어민주당',
    politician_position: '부산광역시장',
    politician_status: '예비후보자',
    title: '지역 발전 기금 조성',
    content: '지역 발전을 위한 기금을 조성하여 사회복지시설 개선에 사용할 예정입니다.',
    category: '복지',
    created_at: '2024-10-14',
    view_count: 380,
    upvotes: 72,
    comment_count: 12,
  },
  {
    id: 3,
    politician_id: 3,
    politician_name: '오수진',
    politician_party: '정의당',
    politician_position: '대구광역시장',
    politician_status: '후보자',
    title: '교육 시설 확충 사업',
    content: '지역 내 학교 시설을 현대화하고 도서관을 확충하는 사업을 추진 중입니다.',
    category: '교육',
    created_at: '2024-10-13',
    view_count: 320,
    upvotes: 58,
    comment_count: 10,
  },
  {
    id: 4,
    politician_id: 4,
    politician_name: '이재민',
    politician_party: '개혁신당',
    politician_position: '인천광역시장',
    politician_status: '당선자',
    title: '환경 보호 캠페인',
    content: '지역의 환경 보호를 위한 캠페인을 전개하고 있습니다. 모든 주민의 참여를 부탁드립니다.',
    category: '환경',
    created_at: '2024-10-12',
    view_count: 280,
    upvotes: 45,
    comment_count: 8,
  },
  {
    id: 5,
    politician_id: 5,
    politician_name: '심상정',
    politician_party: '조국혁신당',
    politician_position: '광주광역시장',
    politician_status: '현직',
    title: '일자리 창출 계획',
    content: '지역 내 중소기업 지원을 통해 일자리 창출을 적극 추진하고 있습니다.',
    category: '경제',
    created_at: '2024-10-11',
    view_count: 240,
    upvotes: 34,
    comment_count: 6,
  },
  {
    id: 6,
    politician_id: 6,
    politician_name: '박영순',
    politician_party: '국민의힘',
    politician_position: '대전광역시장',
    politician_status: '출마자',
    title: '교통 인프라 개선',
    content: '지역의 교통 혼잡을 해소하기 위해 새로운 버스 노선을 개설합니다.',
    category: '교통',
    created_at: '2024-10-10',
    view_count: 200,
    upvotes: 23,
    comment_count: 4,
  },
  {
    id: 7,
    politician_id: 7,
    politician_name: '김혜정',
    politician_party: '더불어민주당',
    politician_position: '울산광역시장',
    politician_status: '예비후보자',
    title: '주민 안전 강화',
    content: '지역의 주민 안전을 위해 보안 시설을 확충하고 순찰을 강화합니다.',
    category: '안전',
    created_at: '2024-10-09',
    view_count: 160,
    upvotes: 12,
    comment_count: 2,
  },
  {
    id: 8,
    politician_id: 8,
    politician_name: '조동현',
    politician_party: '정의당',
    politician_position: '세종시장',
    politician_status: '후보자',
    title: '문화 사업 지원',
    content: '지역 문화 발전을 위해 문화 센터 건립과 문화 행사를 지원합니다.',
    category: '문화',
    created_at: '2024-10-08',
    view_count: 120,
    upvotes: 8,
    comment_count: 1,
  },
  {
    id: 9,
    politician_id: 9,
    politician_name: '윤주미',
    politician_party: '개혁신당',
    politician_position: '경기도지사',
    politician_status: '당선자',
    title: '보건 의료 서비스 개선',
    content: '지역 보건 의료 서비스를 확대하여 주민 건강 관리에 적극 나서겠습니다.',
    category: '보건',
    created_at: '2024-10-07',
    view_count: 80,
    upvotes: 4,
    comment_count: 0,
  },
];

// Mock API Adapter Functions
export const mockAdapterApi = {
  async getHomeData() {
    return {
      aiRanking: MOCK_POLITICIANS.slice(0, 10),
      hotPosts: MOCK_HOT_POSTS,
      politicianPosts: MOCK_POLITICIAN_POSTS.slice(0, 3),
      sidebar: {},
    };
  },

  async getPoliticians() {
    return MOCK_POLITICIANS;
  },

  async getPoliticianById(id: number) {
    const politician = MOCK_POLITICIANS.find((p) => p.id === id);
    if (politician) {
      return {
        id: politician.id,
        name: politician.name,
        party: politician.party,
        region: politician.region,
        position: politician.position,
        category_type: politician.category_type,
        political_status: politician.political_status,
        status: politician.status,
        claude_score: politician.claude_score,
        gpt_score: politician.gpt_score,
        gemini_score: politician.gemini_score,
        grok_score: politician.grok_score,
        perplexity_score: politician.perplexity_score,
        composite_score: politician.composite_score,
        member_rating: politician.member_rating,
        member_rating_count: politician.member_rating_count,
      };
    }
    return null;
  },

  async getHotPosts() {
    return MOCK_HOT_POSTS;
  },

  async getPostById(id: number) {
    const hotPost = MOCK_HOT_POSTS.find((p) => p.id === id);
    if (hotPost) {
      return hotPost;
    }
    const politicianPost = MOCK_POLITICIAN_POSTS.find((p) => p.id === id);
    return politicianPost || null;
  },

  async getCommunityPosts() {
    return [...MOCK_HOT_POSTS, ...MOCK_POLITICIAN_POSTS];
  },

  async getPoliticianPosts() {
    return MOCK_POLITICIAN_POSTS;
  },

  async getSidebarData() {
    return {};
  },

  async getAIRanking(options?: { limit?: number; filterType?: string; filterValue?: string }) {
    const limit = options?.limit || 10;
    return MOCK_POLITICIANS.slice(0, limit);
  },
};

export async function getHomeData() {
  return mockAdapterApi.getHomeData();
}

export async function getPoliticians() {
  return mockAdapterApi.getPoliticians();
}

export async function getPoliticianById(id: number) {
  return mockAdapterApi.getPoliticianById(id);
}

export async function getHotPosts() {
  return mockAdapterApi.getHotPosts();
}

export async function getPostById(id: number) {
  return mockAdapterApi.getPostById(id);
}

export async function getCommunityPosts() {
  return mockAdapterApi.getCommunityPosts();
}

export async function getPoliticianPosts() {
  return mockAdapterApi.getPoliticianPosts();
}

export async function getSidebarData() {
  return mockAdapterApi.getSidebarData();
}

export async function getAIRanking(options?: { limit?: number; filterType?: string; filterValue?: string }) {
  return mockAdapterApi.getAIRanking(options);
}
