/**
 * Mock Data Adapter - Using local mock data for development
 * This adapter bridges frontend UI with mock data from the seed database
 * Expanded with 30 politicians for complete UI display
 */

import type { PoliticianRanking, HotPost, PoliticianPost } from './home';

// Mock data based on seed data - 30 Politicians
export const MOCK_POLITICIANS: PoliticianRanking[] = [
  {
    id: 1,
    name: 'Lee Junseok',
    party: 'PEOPLE_POWER',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 4.2,
    gpt_score: 4.1,
    gemini_score: 4.3,
    grok_score: 4.0,
    perplexity_score: 4.2,
    composite_score: 4.16,
    member_rating: 4.04,
    member_rating_count: 3,
  },
  {
    id: 2,
    name: 'Han Dong-hoon',
    party: 'PEOPLE_POWER',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 4.0,
    gpt_score: 3.9,
    gemini_score: 4.1,
    grok_score: 3.8,
    perplexity_score: 4.0,
    composite_score: 3.96,
    member_rating: 3.82,
    member_rating_count: 3,
  },
  {
    id: 3,
    name: 'Oh Se-hoon',
    party: 'PEOPLE_POWER',
    region: 'Seoul',
    position: 'Mayor',
    status: 'active',
    claude_score: 3.8,
    gpt_score: 3.7,
    gemini_score: 3.9,
    grok_score: 3.6,
    perplexity_score: 3.8,
    composite_score: 3.76,
    member_rating: 3.6,
    member_rating_count: 3,
  },
  {
    id: 4,
    name: 'Lee Jae-myung',
    party: 'DEMOCRATIC',
    region: 'Gyeonggi',
    position: 'Governor',
    status: 'active',
    claude_score: 3.9,
    gpt_score: 3.8,
    gemini_score: 4.0,
    grok_score: 3.7,
    perplexity_score: 3.9,
    composite_score: 3.86,
    member_rating: 3.5,
    member_rating_count: 2,
  },
  {
    id: 5,
    name: 'Shim Sang-jeung',
    party: 'JUSTICE',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 4.1,
    gpt_score: 4.0,
    gemini_score: 4.2,
    grok_score: 3.9,
    perplexity_score: 4.1,
    composite_score: 4.06,
    member_rating: 3.9,
    member_rating_count: 2,
  },
  {
    id: 6,
    name: 'Park Young-sun',
    party: 'DEMOCRATIC',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.95,
    gpt_score: 3.85,
    gemini_score: 4.05,
    grok_score: 3.75,
    perplexity_score: 3.95,
    composite_score: 3.91,
    member_rating: 3.7,
    member_rating_count: 2,
  },
  {
    id: 7,
    name: 'Kim Sung-won',
    party: 'PEOPLE_POWER',
    region: 'Busan',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.5,
    perplexity_score: 3.7,
    composite_score: 3.68,
    member_rating: 3.45,
    member_rating_count: 2,
  },
  {
    id: 8,
    name: 'Choi Byung-hun',
    party: 'DEMOCRATIC',
    region: 'Incheon',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.75,
    gpt_score: 3.65,
    gemini_score: 3.85,
    grok_score: 3.6,
    perplexity_score: 3.75,
    composite_score: 3.72,
    member_rating: 3.5,
    member_rating_count: 3,
  },
  {
    id: 9,
    name: 'Woo Won-shik',
    party: 'DEMOCRATIC',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.85,
    gpt_score: 3.75,
    gemini_score: 3.95,
    grok_score: 3.7,
    perplexity_score: 3.85,
    composite_score: 3.82,
    member_rating: 3.65,
    member_rating_count: 4,
  },
  {
    id: 10,
    name: 'Joo Ho-young',
    party: 'PEOPLE_POWER',
    region: 'Daegu',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.6,
    gpt_score: 3.5,
    gemini_score: 3.7,
    grok_score: 3.4,
    perplexity_score: 3.6,
    composite_score: 3.56,
    member_rating: 3.3,
    member_rating_count: 2,
  },
  {
    id: 11,
    name: 'Park Ji-won',
    party: 'DEMOCRATIC',
    region: 'Jeolla',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.9,
    gpt_score: 3.8,
    gemini_score: 4.0,
    grok_score: 3.75,
    perplexity_score: 3.9,
    composite_score: 3.87,
    member_rating: 3.7,
    member_rating_count: 3,
  },
  {
    id: 12,
    name: 'Kwon Young-se',
    party: 'PEOPLE_POWER',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.55,
    gpt_score: 3.45,
    gemini_score: 3.65,
    grok_score: 3.35,
    perplexity_score: 3.55,
    composite_score: 3.51,
    member_rating: 3.25,
    member_rating_count: 2,
  },
  {
    id: 13,
    name: 'Min Hee-jin',
    party: 'DEMOCRATIC',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.8,
    gpt_score: 3.7,
    gemini_score: 3.9,
    grok_score: 3.65,
    perplexity_score: 3.8,
    composite_score: 3.77,
    member_rating: 3.6,
    member_rating_count: 3,
  },
  {
    id: 14,
    name: 'Im Na-ri',
    party: 'JUSTICE',
    region: 'Gangwon',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.55,
    perplexity_score: 3.7,
    composite_score: 3.67,
    member_rating: 3.5,
    member_rating_count: 2,
  },
  {
    id: 15,
    name: 'Yoon Sang-hyun',
    party: 'PEOPLE_POWER',
    region: 'Busan',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.75,
    gpt_score: 3.65,
    gemini_score: 3.85,
    grok_score: 3.6,
    perplexity_score: 3.75,
    composite_score: 3.72,
    member_rating: 3.55,
    member_rating_count: 2,
  },
  {
    id: 16,
    name: 'Lee Seung-yeol',
    party: 'DEMOCRATIC',
    region: 'Daejeon',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.6,
    gpt_score: 3.5,
    gemini_score: 3.7,
    grok_score: 3.45,
    perplexity_score: 3.6,
    composite_score: 3.57,
    member_rating: 3.35,
    member_rating_count: 2,
  },
  {
    id: 17,
    name: 'Choi Jae-sung',
    party: 'PEOPLE_POWER',
    region: 'Ulsan',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.65,
    gpt_score: 3.55,
    gemini_score: 3.75,
    grok_score: 3.5,
    perplexity_score: 3.65,
    composite_score: 3.62,
    member_rating: 3.4,
    member_rating_count: 2,
  },
  {
    id: 18,
    name: 'Kim Doo-kwan',
    party: 'DEMOCRATIC',
    region: 'Gyeongsa',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.55,
    perplexity_score: 3.7,
    composite_score: 3.67,
    member_rating: 3.45,
    member_rating_count: 2,
  },
  {
    id: 19,
    name: 'Han Ki-ho',
    party: 'PEOPLE_POWER',
    region: 'Jeju',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.5,
    gpt_score: 3.4,
    gemini_score: 3.6,
    grok_score: 3.3,
    perplexity_score: 3.5,
    composite_score: 3.46,
    member_rating: 3.2,
    member_rating_count: 2,
  },
  {
    id: 20,
    name: 'Park Kwang-on',
    party: 'DEMOCRATIC',
    region: 'Incheon',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.8,
    gpt_score: 3.7,
    gemini_score: 3.9,
    grok_score: 3.65,
    perplexity_score: 3.8,
    composite_score: 3.77,
    member_rating: 3.55,
    member_rating_count: 3,
  },
  {
    id: 21,
    name: 'Song Young-gil',
    party: 'DEMOCRATIC',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.75,
    gpt_score: 3.65,
    gemini_score: 3.85,
    grok_score: 3.6,
    perplexity_score: 3.75,
    composite_score: 3.72,
    member_rating: 3.5,
    member_rating_count: 2,
  },
  {
    id: 22,
    name: 'Kim Gi-hyeon',
    party: 'PEOPLE_POWER',
    region: 'Gyeonggi',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.55,
    perplexity_score: 3.7,
    composite_score: 3.67,
    member_rating: 3.45,
    member_rating_count: 2,
  },
  {
    id: 23,
    name: 'Lee Sang-min',
    party: 'PEOPLE_POWER',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.85,
    gpt_score: 3.75,
    gemini_score: 3.95,
    grok_score: 3.7,
    perplexity_score: 3.85,
    composite_score: 3.82,
    member_rating: 3.6,
    member_rating_count: 3,
  },
  {
    id: 24,
    name: 'Park Beom-gyu',
    party: 'DEMOCRATIC',
    region: 'Busan',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.65,
    gpt_score: 3.55,
    gemini_score: 3.75,
    grok_score: 3.5,
    perplexity_score: 3.65,
    composite_score: 3.62,
    member_rating: 3.4,
    member_rating_count: 2,
  },
  {
    id: 25,
    name: 'Yoon Ho-jung',
    party: 'JUSTICE',
    region: 'Seoul',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.6,
    gpt_score: 3.5,
    gemini_score: 3.7,
    grok_score: 3.45,
    perplexity_score: 3.6,
    composite_score: 3.57,
    member_rating: 3.35,
    member_rating_count: 2,
  },
  {
    id: 26,
    name: 'Kim Young-sup',
    party: 'PEOPLE_POWER',
    region: 'Daegu',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.75,
    gpt_score: 3.65,
    gemini_score: 3.85,
    grok_score: 3.6,
    perplexity_score: 3.75,
    composite_score: 3.72,
    member_rating: 3.5,
    member_rating_count: 2,
  },
  {
    id: 27,
    name: 'Lee Nak-yon',
    party: 'DEMOCRATIC',
    region: 'Jeolla',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.9,
    gpt_score: 3.8,
    gemini_score: 4.0,
    grok_score: 3.75,
    perplexity_score: 3.9,
    composite_score: 3.87,
    member_rating: 3.65,
    member_rating_count: 3,
  },
  {
    id: 28,
    name: 'Han Ji-won',
    party: 'PEOPLE_POWER',
    region: 'Incheon',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.7,
    gpt_score: 3.6,
    gemini_score: 3.8,
    grok_score: 3.55,
    perplexity_score: 3.7,
    composite_score: 3.67,
    member_rating: 3.45,
    member_rating_count: 2,
  },
  {
    id: 29,
    name: 'Seo Young-man',
    party: 'DEMOCRATIC',
    region: 'Gwangju',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.8,
    gpt_score: 3.7,
    gemini_score: 3.9,
    grok_score: 3.65,
    perplexity_score: 3.8,
    composite_score: 3.77,
    member_rating: 3.55,
    member_rating_count: 3,
  },
  {
    id: 30,
    name: 'Jo Seung-rae',
    party: 'PEOPLE_POWER',
    region: 'Gyeonggi',
    position: 'National Assembly',
    status: 'active',
    claude_score: 3.65,
    gpt_score: 3.55,
    gemini_score: 3.75,
    grok_score: 3.5,
    perplexity_score: 3.65,
    composite_score: 3.62,
    member_rating: 3.4,
    member_rating_count: 2,
  },
];

// 15 Hot Posts for 5x3 grid
export const MOCK_HOT_POSTS: HotPost[] = [
  {
    id: 1,
    title: '이준석 의원 정책 발표 - AI 경제 정책 분석',
    content: 'AI 기술을 활용한 경제 정책에 대한 종합 분석',
    category: 'politics',
    view_count: 2543,
    upvotes: 456,
    downvotes: 23,
    comment_count: 123,
    hot_score: 8.5,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    author_username: 'user1',
  },
  {
    id: 2,
    title: '한동훈 장관 출마 공식 선언',
    content: '한동훈 전 법무부 장관이 대선 출마를 공식 선언',
    category: 'breaking',
    view_count: 4521,
    upvotes: 892,
    downvotes: 45,
    comment_count: 287,
    hot_score: 9.2,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    author_username: 'news_bot',
  },
  {
    id: 3,
    title: '오세훈 서울시장, 교통 정책 대개혁 발표',
    content: '서울 지하철 요금 인상 및 버스 개편안 공개',
    category: 'policy',
    view_count: 3124,
    upvotes: 567,
    downvotes: 234,
    comment_count: 145,
    hot_score: 7.8,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    author_username: 'admin',
  },
  {
    id: 4,
    title: '야권 정치인들 AI 활용 정책 대담',
    content: 'AI 정책을 중심으로 한 야권 정치인 좌담회',
    category: 'interview',
    view_count: 1876,
    upvotes: 345,
    downvotes: 12,
    comment_count: 98,
    hot_score: 6.9,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    author_username: 'journalist_kim',
  },
  {
    id: 5,
    title: '정치인 평가 플랫폼 AI 모델 비교 분석',
    content: 'Claude vs GPT vs Gemini 평가 모델 비교 검토',
    category: 'analysis',
    view_count: 2341,
    upvotes: 678,
    downvotes: 34,
    comment_count: 156,
    hot_score: 8.1,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    author_username: 'tech_analyst',
  },
  {
    id: 6,
    title: '이재명 경기도지사 경제 정책 발표',
    content: '경기도 일자리 창출 정책 및 경제 활성화 방안 공개',
    category: 'policy',
    view_count: 2891,
    upvotes: 512,
    downvotes: 28,
    comment_count: 134,
    hot_score: 8.0,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    author_username: 'policy_observer',
  },
  {
    id: 7,
    title: '심상정 정의당 대표 복지 정책 강화',
    content: '기본소득 및 사회안전망 강화 방안에 대한 심상정 대표의 입장',
    category: 'politics',
    view_count: 1654,
    upvotes: 421,
    downvotes: 67,
    comment_count: 89,
    hot_score: 7.2,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    author_username: 'social_policy',
  },
  {
    id: 8,
    title: '우원식 의원 외교정책 스페셜 인터뷰',
    content: '한미동맹 강화 및 동북아 평화 구축 방안 논의',
    category: 'interview',
    view_count: 1923,
    upvotes: 356,
    downvotes: 19,
    comment_count: 76,
    hot_score: 7.5,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    author_username: 'diplomat_news',
  },
  {
    id: 9,
    title: '박지원 의원 국방정책 세미나',
    content: '한반도 평화와 국방력 강화를 위한 통합 전략 제시',
    category: 'policy',
    view_count: 2156,
    upvotes: 478,
    downvotes: 32,
    comment_count: 112,
    hot_score: 7.9,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    author_username: 'defense_expert',
  },
  {
    id: 10,
    title: '여러 정당 대표들 교육정책 토론',
    content: '입시제도 개편과 대학 개혁에 대한 다양한 관점 공유',
    category: 'discussion',
    view_count: 1734,
    upvotes: 312,
    downvotes: 41,
    comment_count: 98,
    hot_score: 7.0,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    author_username: 'education_forum',
  },
  {
    id: 11,
    title: '녹색 정책 토론회 - 환경 이슈',
    content: '기후변화 대응 및 재정에너지 전환에 대한 각 당의 입장',
    category: 'policy',
    view_count: 1452,
    upvotes: 289,
    downvotes: 24,
    comment_count: 67,
    hot_score: 6.8,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 270).toISOString(),
    author_username: 'green_future',
  },
  {
    id: 12,
    title: '부동산 정책 집중 분석 - 최근 동향',
    content: '주택담보대출금리 인상과 아파트 가격 분석',
    category: 'analysis',
    view_count: 3245,
    upvotes: 634,
    downvotes: 156,
    comment_count: 201,
    hot_score: 8.3,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    author_username: 'real_estate_analyst',
  },
  {
    id: 13,
    title: '노동정책 어느 쪽이 더 나을까?',
    content: '최저임금, 근로시간, 노동조합에 대한 각 정당의 입장 비교',
    category: 'comparison',
    view_count: 1876,
    upvotes: 398,
    downvotes: 78,
    comment_count: 145,
    hot_score: 7.4,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 330).toISOString(),
    author_username: 'labor_watch',
  },
  {
    id: 14,
    title: '청년 정책 공약 비교 분석',
    content: '청년 일자리, 주거, 교육에 대한 각 후보 공약 정리',
    category: 'analysis',
    view_count: 2134,
    upvotes: 521,
    downvotes: 43,
    comment_count: 178,
    hot_score: 8.2,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    author_username: 'youth_issue',
  },
  {
    id: 15,
    title: '여성 정책 어젠다 종합 정리',
    content: '성평등, 보육, 일생활균형에 대한 정치인별 공약 분석',
    category: 'policy',
    view_count: 1623,
    upvotes: 445,
    downvotes: 35,
    comment_count: 123,
    hot_score: 7.6,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 390).toISOString(),
    author_username: 'equality_now',
  },
];

// 9 Politician Posts for 3x3 grid
export const MOCK_POLITICIAN_POSTS: PoliticianPost[] = [
  {
    id: 101,
    politician_id: 1,
    politician_name: 'Lee Junseok',
    politician_party: 'PEOPLE_POWER',
    politician_position: 'National Assembly',
    politician_status: 'active',
    content: '국민과의 대화 시간을 통해 지난주 경제 정책에 대해 설명했습니다. 여러분의 의견을 듣고 더 나은 정책을 만들겠습니다.',
    view_count: 543,
    upvotes: 78,
    comment_count: 23,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 102,
    politician_id: 2,
    politician_name: 'Han Dong-hoon',
    politician_party: 'PEOPLE_POWER',
    politician_position: 'National Assembly',
    politician_status: 'active',
    content: '법치주의 강화를 위한 사법 개혁안을 국회에 제출했습니다. 전문가와 국민의 다양한 의견을 수렴하겠습니다.',
    view_count: 621,
    upvotes: 92,
    comment_count: 34,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 103,
    politician_id: 3,
    politician_name: 'Oh Se-hoon',
    politician_party: 'PEOPLE_POWER',
    politician_position: 'Mayor',
    politician_status: 'active',
    content: '서울 지하철 9호선 연장 사업이 순조롭게 진행 중입니다. 올해 상반기 개통을 목표로 추진 중이니 기대해주세요.',
    view_count: 854,
    upvotes: 145,
    comment_count: 56,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
  {
    id: 104,
    politician_id: 4,
    politician_name: 'Lee Jae-myung',
    politician_party: 'DEMOCRATIC',
    politician_position: 'Governor',
    politician_status: 'active',
    content: '경기도 청년 일자리 창출 프로젝트가 본격적으로 시작됩니다. 더 많은 청년들이 안정적인 일자리를 갖길 바랍니다.',
    view_count: 712,
    upvotes: 156,
    comment_count: 42,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 105,
    politician_id: 5,
    politician_name: 'Shim Sang-jeung',
    politician_party: 'JUSTICE',
    politician_position: 'National Assembly',
    politician_status: 'active',
    content: '국민의 삶을 더욱 풍요롭게 하기 위한 기본소득제 도입을 위해 노력하겠습니다. 여러분의 지지가 큰 힘입니다.',
    view_count: 534,
    upvotes: 203,
    comment_count: 67,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 106,
    politician_id: 6,
    politician_name: 'Park Young-sun',
    politician_party: 'DEMOCRATIC',
    politician_position: 'National Assembly',
    politician_status: 'active',
    content: '여성 평등과 사회안전망 강화를 위해 새로운 법안을 발의했습니다. 모든 국민이 동등한 기회를 갖는 사회를 만들겠습니다.',
    view_count: 645,
    upvotes: 178,
    comment_count: 51,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 107,
    politician_id: 9,
    politician_name: 'Woo Won-shik',
    politician_party: 'DEMOCRATIC',
    politician_position: 'National Assembly',
    politician_status: 'active',
    content: '국회 운영에 투명성과 효율성을 더하기 위해 개혁 방안을 제시했습니다. 국민이 중심이 되는 국회가 되도록 하겠습니다.',
    view_count: 489,
    upvotes: 134,
    comment_count: 38,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
  },
  {
    id: 108,
    politician_id: 11,
    politician_name: 'Park Ji-won',
    politician_party: 'DEMOCRATIC',
    politician_position: 'National Assembly',
    politician_status: 'active',
    content: '대한민국의 평화와 번영을 위해 외교정책에 역점을 두겠습니다. 함께 더 좋은 미래를 만들어 나가겠습니다.',
    view_count: 567,
    upvotes: 167,
    comment_count: 44,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 109,
    politician_id: 14,
    politician_name: 'Im Na-ri',
    politician_party: 'JUSTICE',
    politician_position: 'National Assembly',
    politician_status: 'active',
    content: '환경보호와 지속 가능한 발전을 동시에 이룰 수 있는 정책을 제안합니다. 녹색 경제로의 전환이 필요합니다.',
    view_count: 423,
    upvotes: 98,
    comment_count: 29,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
  },
];

export const MOCK_SIDEBAR_DATA = {
  stats: {
    total_count: 30,
    active_count: 30,
    candidate_count: 0,
    new_this_week: 5,
  },
  trendingPoliticians: [
    {
      id: 1,
      name: 'Lee Junseok',
      position: 'National Assembly',
      party: 'PEOPLE_POWER',
      score_change: 0.3,
    },
    {
      id: 5,
      name: 'Shim Sang-jeung',
      position: 'National Assembly',
      party: 'JUSTICE',
      score_change: 0.2,
    },
    {
      id: 9,
      name: 'Woo Won-shik',
      position: 'National Assembly',
      party: 'DEMOCRATIC',
      score_change: 0.15,
    },
    {
      id: 11,
      name: 'Park Ji-won',
      position: 'National Assembly',
      party: 'DEMOCRATIC',
      score_change: 0.12,
    },
  ],
  realtimeStats: {
    posts_last_hour: 34,
    comments_last_hour: 127,
    active_users_24h: 892,
  },
  connectedServices: [
    {
      id: 1,
      name: 'National Assembly',
      icon: '🏛️',
      description: '국회 공식 데이터 연동',
    },
    {
      id: 2,
      name: 'News API',
      icon: '📰',
      description: '실시간 뉴스 데이터',
    },
  ],
  ad: null,
};

// Export adapter functions
export const mockAdapterApi = {
  getHomeData: async () => {
    return {
      aiRanking: MOCK_POLITICIANS.slice(0, 10),
      hotPosts: MOCK_HOT_POSTS,
      politicianPosts: MOCK_POLITICIAN_POSTS,
      sidebar: MOCK_SIDEBAR_DATA,
    };
  },

  getAIRanking: async (options?: {
    limit?: number;
    filterType?: 'region' | 'party' | 'position';
    filterValue?: string;
  }) => {
    let result = [...MOCK_POLITICIANS];

    if (options?.filterType && options?.filterValue) {
      const filterKey = options.filterType as keyof typeof MOCK_POLITICIANS[0];
      result = result.filter((p) => {
        const value = p[filterKey];
        return value === options.filterValue || String(value).includes(options.filterValue);
      });
    }

    result = result.sort((a, b) => (b.composite_score || 0) - (a.composite_score || 0));

    return result.slice(0, options?.limit || 10);
  },

  getHotPosts: async (limit = 15) => {
    return MOCK_HOT_POSTS.slice(0, limit);
  },

  getPoliticianPosts: async (limit = 9) => {
    return MOCK_POLITICIAN_POSTS.slice(0, limit);
  },

  getSidebarData: async () => {
    return MOCK_SIDEBAR_DATA;
  },
};

// Extended functions for filtering
mockAdapterApi.getPoliticiansWithFiltering = (filters: any, page: number = 1, itemsPerPage: number = 12) => {
  let result = [...MOCK_POLITICIANS];

  if (filters.searchName) {
    result = result.filter((p) =>
      p.name.toLowerCase().includes(filters.searchName.toLowerCase())
    );
  }
  if (filters.searchParty) {
    result = result.filter((p) =>
      p.party.toLowerCase().includes(filters.searchParty.toLowerCase())
    );
  }
  if (filters.searchRegion) {
    result = result.filter((p) =>
      p.region.toLowerCase().includes(filters.searchRegion.toLowerCase())
    );
  }

  if (filters.parties && filters.parties.length > 0) {
    result = result.filter((p) => filters.parties.includes(p.party));
  }
  if (filters.regions && filters.regions.length > 0) {
    result = result.filter((p) => filters.regions.includes(p.region));
  }
  if (filters.positions && filters.positions.length > 0) {
    result = result.filter((p) => filters.positions.includes(p.position));
  }

  if (filters.sortBy === 'name') {
    result.sort((a, b) =>
      filters.sortOrder === 'desc'
        ? b.name.localeCompare(a.name, 'ko-KR')
        : a.name.localeCompare(b.name, 'ko-KR')
    );
  } else if (filters.sortBy === 'rating') {
    result.sort((a, b) =>
      filters.sortOrder === 'desc'
        ? (b.member_rating || 0) - (a.member_rating || 0)
        : (a.member_rating || 0) - (b.member_rating || 0)
    );
  } else if (filters.sortBy === 'popularity') {
    result.sort((a, b) =>
      filters.sortOrder === 'desc'
        ? (b.member_rating_count || 0) - (a.member_rating_count || 0)
        : (a.member_rating_count || 0) - (b.member_rating_count || 0)
    );
  }

  const total = result.length;
  const from = (page - 1) * itemsPerPage;
  const to = from + itemsPerPage;
  const data = result.slice(from, to);

  return { data, total };
};

mockAdapterApi.getPoliticianById = (id: number) => {
  return MOCK_POLITICIANS.find((p) => p.id === id);
};

// Community Posts Mock Data
export const MOCK_COMMUNITY_POSTS = [
  {
    id: 1,
    title: '이준석 의원의 최신 정책 평가하기',
    content: '이준석 의원의 최근 AI 경제 정책에 대해 어떻게 생각하시나요? 긍정적인 의견과 비판적 의견을 모두 환영합니다.',
    category: 'discussion',
    author_username: 'user1',
    author_avatar: '👤',
    view_count: 342,
    comment_count: 28,
    upvotes: 87,
    downvotes: 3,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 2,
    title: '[질문] 정치인 평가 플랫폼 사용 방법을 알려주세요',
    content: '처음 이 플랫폼을 사용하는데 정치인을 검색하고 평가하는 방법이 잘 모르겠습니다. 누가 좀 알려줄 수 있나요?',
    category: 'question',
    author_username: 'newuser_2024',
    author_avatar: '👤',
    view_count: 156,
    comment_count: 12,
    upvotes: 34,
    downvotes: 1,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 3,
    title: '한동훈 장관 출마 선언에 대한 평가',
    content: '한동훈 전 법무부 장관이 대선 출마를 선언했습니다. 정치인 평가 플랫폼에서의 그의 평점을 보니 상당히 높네요. 실제로 어떻게 평가하시나요?',
    category: 'news',
    author_username: 'politics_fan',
    author_avatar: '👤',
    view_count: 523,
    comment_count: 45,
    upvotes: 156,
    downvotes: 23,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 4,
    title: '오세훈 서울시장 교통 정책 평가하기',
    content: '서울 지하철 요금 인상에 대해 어떻게 생각하세요? 예전보다 서비스가 좋아졌나요?',
    category: 'discussion',
    author_username: 'seoul_resident',
    author_avatar: '👤',
    view_count: 289,
    comment_count: 34,
    upvotes: 67,
    downvotes: 12,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 5,
    title: '[자유게시판] AI 평가 시스템의 정확도에 대해서',
    content: '이 플랫폼의 AI 모델들이 정치인을 공정하게 평가할 수 있을까요? 다양한 AI 모델의 평가를 비교해보니 차이가 꽤 크네요.',
    category: 'general',
    author_username: 'tech_discussion',
    author_avatar: '👤',
    view_count: 412,
    comment_count: 56,
    upvotes: 134,
    downvotes: 18,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 6,
    title: '[뉴스] 새로운 정치인 30명 플랫폼에 추가되었습니다',
    content: '정치인 찾기 플랫폼에 더 많은 정치인들이 추가되었습니다. 다양한 정치인들을 비교하고 평가할 수 있게 되었습니다.',
    category: 'news',
    author_username: 'admin_news',
    author_avatar: '👤',
    view_count: 678,
    comment_count: 78,
    upvotes: 245,
    downvotes: 8,
    is_hot: true,
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
  {
    id: 7,
    title: '[토론] 정치인 평가 기준은 무엇이어야 할까?',
    content: '정치인을 평가할 때 어떤 기준을 가장 중요하게 생각하시나요? 정책 실적? 도덕성? 소통 능력? 토론을 나누고 싶습니다.',
    category: 'discussion',
    author_username: 'thoughtful_citizen',
    author_avatar: '👤',
    view_count: 234,
    comment_count: 42,
    upvotes: 89,
    downvotes: 5,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
  {
    id: 8,
    title: '정치인 평가 플랫폼 개선 의견 모으기',
    content: '이 플랫폼을 더 좋게 만들 수 있는 아이디어가 있으신가요? 다양한 의견을 환영합니다. 개발팀이 참고할 예정입니다.',
    category: 'general',
    author_username: 'feedback_team',
    author_avatar: '👤',
    view_count: 145,
    comment_count: 23,
    upvotes: 56,
    downvotes: 2,
    is_hot: false,
    created_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
  },
];

// Add getCommunityPosts function to mockAdapterApi
mockAdapterApi.getCommunityPosts = (category = 'all', searchTerm = '', page = 1, limit = 20) => {
  let posts = [...MOCK_COMMUNITY_POSTS];

  // Filter by category
  if (category !== 'all') {
    posts = posts.filter(post => post.category === category);
  }

  // Filter by search term
  if (searchTerm) {
    posts = posts.filter(post =>
      post.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      post.content.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }

  // Sort by created_at (latest first)
  posts.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

  // Pagination
  const total = posts.length;
  const from = (page - 1) * limit;
  const to = from + limit;
  const data = posts.slice(from, to);

  return { data, total, page, limit };
};
