-- Supabase project_grid 테이블 업데이트
-- 모든 assigned_agent에서 '2차' 표현 제거

UPDATE project_grid SET assigned_agent = '1차: devops-troubleshooter' WHERE task_id = 'P1O1';
UPDATE project_grid SET assigned_agent = '1차: database-developer' WHERE task_id = 'P1D1';
UPDATE project_grid SET assigned_agent = '1차: database-developer' WHERE task_id = 'P1D2';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P1D3';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P1D4';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P1D5';
UPDATE project_grid SET assigned_agent = '1차: backend-developer' WHERE task_id = 'P1BI1';
UPDATE project_grid SET assigned_agent = '1차: backend-developer' WHERE task_id = 'P1BI2';
UPDATE project_grid SET assigned_agent = 'backend-developer' WHERE task_id = 'P1BI3';
UPDATE project_grid SET assigned_agent = '1차: api-designer' WHERE task_id = 'P1BA1';
UPDATE project_grid SET assigned_agent = '1차: api-designer' WHERE task_id = 'P1BA2';
UPDATE project_grid SET assigned_agent = '1차: api-designer' WHERE task_id = 'P1BA3';
UPDATE project_grid SET assigned_agent = '1차: api-designer' WHERE task_id = 'P1BA4';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P1F1';
UPDATE project_grid SET assigned_agent = '1차: ui-designer' WHERE task_id = 'P1F2';
UPDATE project_grid SET assigned_agent = '1차: frontend-developer' WHERE task_id = 'P1F3';
UPDATE project_grid SET assigned_agent = '1차: frontend-developer' WHERE task_id = 'P1F4';
UPDATE project_grid SET assigned_agent = '1차: frontend-developer' WHERE task_id = 'P1F5';
UPDATE project_grid SET assigned_agent = '1차: test-engineer' WHERE task_id = 'P1T1';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P1T2';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P2F1';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P2F2';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P2F3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA1';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA2';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA4';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA5';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA6';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA7';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA8';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA9';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P2BA10';
UPDATE project_grid SET assigned_agent = 'security-specialist' WHERE task_id = 'P2BA11';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P2D1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P2D2';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P2D3';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P2D4';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P2D5';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P2D6';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P2D7';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P2T1';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P2T2';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P2O1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D2';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D3';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D4';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D5';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D6';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D7';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P3D8';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA1';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA2';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA4';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA5';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA6';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA7';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA8';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA9';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA10';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA11';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P3BA12';
UPDATE project_grid SET assigned_agent = 'security-specialist' WHERE task_id = 'P3BA13';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P3F1';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P3F2';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P3F3';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P3F4';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P3F5';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P3F6';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P3T1';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P3T2';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P3T3';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P3T4';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P3O1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P4D1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P4D2';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P4D3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P4BA1';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P4BA2';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P4BA3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P4BA4';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P4BA5';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P4F1';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P4F2';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P4F3';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P4T1';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P4T2';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P4O1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P5D1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P5D2';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P5BA1';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P5BA2';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P5BA3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P5BA4';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P5BA5';
UPDATE project_grid SET assigned_agent = 'security-specialist' WHERE task_id = 'P5BA6';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P5F1';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P5F2';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P5T1';
UPDATE project_grid SET assigned_agent = 'test-engineer' WHERE task_id = 'P5T2';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P6D1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P6D2';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P6D3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA1';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA2';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA4';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA5';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA6';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA7';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA8';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P6BA9';
UPDATE project_grid SET assigned_agent = 'security-specialist' WHERE task_id = 'P6BA10';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P6F1';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P6F2';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P6F3';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P6F4';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P6F5';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P6F6';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P6F7';
UPDATE project_grid SET assigned_agent = 'code-reviewer' WHERE task_id = 'P6T1';
UPDATE project_grid SET assigned_agent = 'code-reviewer' WHERE task_id = 'P6T2';
UPDATE project_grid SET assigned_agent = 'code-reviewer' WHERE task_id = 'P6T3';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P6O1';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P7BA1';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P7BA2';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P7BA3';
UPDATE project_grid SET assigned_agent = 'api-designer' WHERE task_id = 'P7BA4';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P7F1';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P7F2';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P7F3';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P7F4';
UPDATE project_grid SET assigned_agent = 'frontend-developer' WHERE task_id = 'P7F5';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P7D1';
UPDATE project_grid SET assigned_agent = 'database-developer' WHERE task_id = 'P7D2';
UPDATE project_grid SET assigned_agent = 'code-reviewer' WHERE task_id = 'P7T1';
UPDATE project_grid SET assigned_agent = 'code-reviewer' WHERE task_id = 'P7T2';
UPDATE project_grid SET assigned_agent = 'code-reviewer' WHERE task_id = 'P7T3';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P7O1';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P7O2';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P7O3';
UPDATE project_grid SET assigned_agent = 'devops-troubleshooter' WHERE task_id = 'P7O4';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P4F4';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P5F3';
UPDATE project_grid SET assigned_agent = 'ui-designer' WHERE task_id = 'P5F4';
