# Application Alert Rules
groups:
  - name: application_alerts
    interval: 30s
    rules:
      # High Error Rate
      - alert: HighErrorRate
        expr: |
          rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"

      # Slow Response Time
      - alert: SlowResponseTime
        expr: |
          histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 10m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "Slow response time detected"
          description: "95th percentile response time is {{ $value }}s (threshold: 1s)"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: |
          (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} (threshold: 90%)"

      # High CPU Usage
      - alert: HighCPUUsage
        expr: |
          100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value | humanize }}% (threshold: 80%)"

      # Application Down
      - alert: ApplicationDown
        expr: up{job="frontend"} == 0 or up{job="backend"} == 0
        for: 2m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "Application is down"
          description: "{{ $labels.job }} has been down for more than 2 minutes"

      # Database Connection Issues
      - alert: DatabaseConnectionIssues
        expr: |
          rate(database_connection_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "Database connection issues"
          description: "Database connection error rate is {{ $value }}/s"

      # High Request Rate
      - alert: HighRequestRate
        expr: |
          rate(http_requests_total[5m]) > 1000
        for: 10m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "Unusually high request rate"
          description: "Request rate is {{ $value }}/s (threshold: 1000/s)"

      # Disk Space Low
      - alert: DiskSpaceLow
        expr: |
          (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 10m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Low disk space"
          description: "Available disk space is {{ $value | humanizePercentage }}"

      # SSL Certificate Expiring
      - alert: SSLCertificateExpiring
        expr: |
          probe_ssl_earliest_cert_expiry - time() < 30 * 24 * 3600
        for: 1h
        labels:
          severity: warning
          component: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate expires in {{ $value | humanizeDuration }}"

      # Too Many Failed Login Attempts
      - alert: TooManyFailedLogins
        expr: |
          rate(auth_failed_attempts_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High number of failed login attempts"
          description: "Failed login rate is {{ $value }}/s (possible attack)"

      # Cache Hit Rate Low
      - alert: LowCacheHitRate
        expr: |
          rate(cache_hits_total[5m]) / rate(cache_requests_total[5m]) < 0.7
        for: 15m
        labels:
          severity: info
          component: cache
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 70%)"

      # Database Query Slow
      - alert: SlowDatabaseQueries
        expr: |
          histogram_quantile(0.95, rate(database_query_duration_seconds_bucket[5m])) > 0.5
        for: 10m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Slow database queries"
          description: "95th percentile query time is {{ $value }}s (threshold: 0.5s)"

      # API Rate Limit Hit
      - alert: RateLimitHit
        expr: |
          rate(rate_limit_exceeded_total[5m]) > 5
        for: 5m
        labels:
          severity: info
          component: application
        annotations:
          summary: "Rate limit frequently exceeded"
          description: "Rate limit exceeded {{ $value }} times/s"

      # Deployment Health Check Failed
      - alert: DeploymentHealthCheckFailed
        expr: |
          probe_success{job="blackbox"} == 0
        for: 3m
        labels:
          severity: critical
          component: deployment
        annotations:
          summary: "Health check failed"
          description: "{{ $labels.instance }} health check has been failing for 3 minutes"
